export const carrotOrange: string;
export const coral: string;
export const curulean: string;
export const orange: string;
export const paynesGray: string;
export const pistachio: string;
export const red: string;
export const saffron: string;
export const zomp: string;
